apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberoot-agent
  namespace: kuberoot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberoot-agent-readonly
rules:
  - apiGroups: [""]
    resources: ["pods", "events", "services", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberoot-agent-readonly
subjects:
  - kind: ServiceAccount
    name: kuberoot-agent
    namespace: kuberoot
roleRef:
  kind: ClusterRole
  name: kuberoot-agent-readonly
  apiGroup: rbac.authorization.k8s.io
