apiVersion: v1
kind: Secret
metadata:
  name: kuberoot-agent-secret
  namespace: kuberoot
type: Opaque
stringData:
  # Generate with: ./cmd/keygen/main.go or use a UUIDv4
  KUBEROOT_API_KEY: replace-with-api-key-from-keygen
