apiVersion: v1
kind: Service
metadata:
  name: kuberoot-backend
  namespace: kuberoot
spec:
  selector:
    app: kuberoot-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
