apiVersion: v1
kind: Secret
metadata:
  name: kuberoot-backend-secret
  namespace: kuberoot
type: Opaque
stringData:
  DATABASE_URL: postgres://kuberoot:kuberoot-pass@kuberoot-postgres:5432/kuberoot?sslmode=disable
