apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - agent-configmap.yaml
  - agent-secret.yaml
  - agent-rbac.yaml
  - agent-deployment.yaml
