apiVersion: v1
kind: Secret
metadata:
  name: kuberoot-postgres-secret
  namespace: kuberoot
type: Opaque
stringData:
  POSTGRES_USER: kuberoot
  POSTGRES_PASSWORD: kuberoot-pass
  POSTGRES_DB: kuberoot
