apiVersion: v1
kind: Service
metadata:
  name: kuberoot-postgres
  namespace: kuberoot
spec:
  selector:
    app: kuberoot-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
